import { createClient } from '@/lib/supabase/server';
import Link from 'next/link';

export default async function HomePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: profile } = user ? await supabase.from('profiles').select('role').eq('id', user.id).single() : { data: null };
  return <main className="space-y-8"><section className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 p-8 text-white shadow-2xl sm:p-14"><div className="max-w-2xl space-y-5"><span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-300">แพลตฟอร์มสุขภาพดิจิทัล</span><h1 className="text-4xl font-black tracking-tight sm:text-5xl">ดูแลสุขภาพอย่างมั่นใจ</h1><p className="text-base leading-relaxed text-slate-300">จัดการข้อมูลสุขภาพส่วนตัวอย่างปลอดภัย พร้อมเครื่องมือที่ใช้งานง่ายและเป็นส่วนตัว</p><div className="flex flex-wrap gap-3 pt-3">{user ? <Link href="/profile" className="rounded-xl bg-emerald-400 px-6 py-3 text-sm font-bold text-slate-950 shadow-lg">จัดการโปรไฟล์</Link> : <Link href="/signup" className="rounded-xl bg-emerald-400 px-6 py-3 text-sm font-bold text-slate-950 shadow-lg">สมัครสมาชิก</Link>}{user && profile?.role === 'admin' && <Link href="/admin" className="rounded-xl border border-emerald-400/40 px-6 py-3 text-sm font-semibold text-emerald-200">จัดการระบบ</Link>}</div></div></section><section className="grid gap-5 md:grid-cols-3">{[['🔒','ปลอดภัยและเป็นส่วนตัว','ปกป้องข้อมูลด้วยระบบสิทธิ์การเข้าถึง'],['✨','ใช้งานง่าย','รองรับมือถือ แท็บเล็ต และคอมพิวเตอร์'],['⚙️','จัดการได้ในที่เดียว','ดูแลข้อมูลบัญชีได้อย่างรวดเร็ว']].map(([icon,title,text])=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-4 text-2xl">{icon}</div><h2 className="font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm text-slate-600">{text}</p></article>)}</section></main>;
}
