import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'

export default function AddAppointment() {
  const location = useLocation(); const navigate = useNavigate(); const selectedDate = new URLSearchParams(location.search).get('date') || new Date().toISOString().slice(0, 10)
  const [form, setForm] = useState({ date: selectedDate, time: '09:00', symptoms: '', name: '', contact: '', provider: '', notes: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [symptomsError, setSymptomsError] = useState('')
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  async function handleSubmit(event) { event.preventDefault(); if (saving) return; if (!form.symptoms.trim()) { setSymptomsError('กรุณากรอกอาการที่ติดตาม'); return } setSymptomsError(''); setSaving(true); setError(''); try { const appointmentDate = new Date(`${form.date}T${form.time}`); if (Number.isNaN(appointmentDate.getTime())) throw new Error('วันหรือเวลานัดหมายไม่ถูกต้อง'); const { data: { user }, error: authError } = await supabase.auth.getUser(); if (authError) throw authError; if (!user) throw new Error('กรุณาเข้าสู่ระบบก่อนยืนยันการนัดหมาย'); const { error: insertError } = await supabase.from('health_appointments').insert({ user_id: user.id, symptoms: form.symptoms.trim(), contact_name: form.name.trim() || null, contact_value: form.contact.trim() || null, appointment_at: appointmentDate.toISOString(), provider: form.provider || null, notes: form.notes || null }); if (insertError) throw insertError; navigate('/appointments', { replace: true }) } catch (saveError) { setError(saveError.message || 'บันทึกนัดหมายไม่สำเร็จ กรุณาตรวจสอบข้อมูลแล้วลองใหม่'); setSaving(false) } }
  return <main className="appointment-calendar-page"><header className="appointment-calendar-header"><Link to="/appointments">← กลับไปปฏิทินนัดหมาย</Link><h1>เพิ่มรายละเอียดนัดหมาย</h1><p>กรอกข้อมูลนัดหมายของคุณ</p></header><form className="appointment-form-page" onSubmit={handleSubmit}><label>อาการที่ติดตาม<span className="required-field"> *</span><textarea rows="4" value={form.symptoms} onChange={(event) => { update('symptoms', event.target.value); if (event.target.value.trim()) setSymptomsError('') }} placeholder="เช่น ไอ เหนื่อย หรือไม่มีอาการ" required aria-invalid={Boolean(symptomsError)} aria-describedby={symptomsError ? 'symptoms-error' : undefined} /></label>{symptomsError && <p id="symptoms-error" className="appointment-field-error" role="alert">{symptomsError}</p>}<label>ชื่อแพทย์หรือพยาบาล (ถ้ามี)<input value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label>เบอร์โทรหรืออีเมลสำหรับติดต่อ (ถ้ามี)<input value={form.contact} onChange={(event) => update('contact', event.target.value)} /></label><label>วันที่นัดหมาย<input type="date" value={form.date} onChange={(event) => update('date', event.target.value)} required /></label><label>เวลานัดหมาย<input type="time" value={form.time} onChange={(event) => update('time', event.target.value)} required /></label><label>รายละเอียดเพิ่มเติม (ถ้ามี)<textarea rows="5" value={form.notes} onChange={(event) => update('notes', event.target.value)} /></label><div className="appointment-form-actions"><Link to="/appointments">ยกเลิกการกรอก</Link><button type="submit" disabled={saving}>{saving ? 'กำลังบันทึกนัดหมาย...' : 'ยืนยันการนัดหมาย'}</button></div>{error && <p className="appointment-error" role="alert">{error}</p>}</form></main>
}
