import { useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
export default function ExerciseDetail() {
  const { state } = useLocation(); const exercise = state?.exercise || 'เดินเร็ว'; const target = Number(state?.duration || 30) * 60; const [seconds, setSeconds] = useState(0); const [running, setRunning] = useState(false); const [note, setNote] = useState(''); const [history, setHistory] = useState(() => JSON.parse(localStorage.getItem('exercise-history') || '[]'))
  useEffect(() => { if (!running) return undefined; const timer = window.setInterval(() => setSeconds((value) => value + 1), 1000); return () => window.clearInterval(timer) }, [running])
  const save = () => { const item = { exercise, seconds, note, completedAt: new Date().toISOString() }; const next = [item, ...history].slice(0, 10); setHistory(next); localStorage.setItem('exercise-history', JSON.stringify(next)); setRunning(false) }
  const format = (value) => String(Math.floor(value / 60)).padStart(2, '0') + ':' + String(value % 60).padStart(2, '0')
  return <main className="health-planning-page exercise-detail-page"><header className="health-planning-header"><Link to="/workout-plan" className="health-planning-back">← กลับตารางรายสัปดาห์</Link><h1>{exercise}</h1><p>ทำกิจกรรมตามเวลาที่แนะนำ {format(target)} นาที</p></header><section className="exercise-detail-card"><div className="exercise-visual" aria-label={'ภาพประกอบ ' + exercise}>🏃</div><div className="exercise-timer" role="timer">{format(seconds)}</div><div className="health-wizard-actions"><button className="health-primary-button" type="button" onClick={() => setRunning(!running)}>{running ? 'หยุดชั่วคราว' : 'เริ่มต้น'}</button><button className="health-secondary-button" type="button" onClick={() => setSeconds(0)}>รีเซ็ต</button></div><label>เพิ่มความคิดเห็น<textarea rows="3" value={note} onChange={(event) => setNote(event.target.value)} placeholder="รู้สึกอย่างไรหลังออกกำลังกาย" /></label><button className="health-primary-button" type="button" onClick={save}>บันทึกกิจกรรม</button></section><section className="health-records exercise-history"><strong>ประวัติการออกกำลังกาย</strong>{history.length ? history.map((item) => <span key={item.completedAt}>{item.exercise} · {format(item.seconds)} · {new Date(item.completedAt).toLocaleDateString('th-TH')} {item.note ? '· ' + item.note : ''}</span>) : <small>ยังไม่มีประวัติ</small>}</section></main>
}
