import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const initial = { age: '', weight: '', height: '', days: '3', intensity: 'เบา', condition: 'ไม่มีโรคประจำตัว', otherCondition: '' }
const num = (value) => Number.isFinite(Number(value)) && Number(value) > 0 ? Number(value) : null

export default function ExercisePlan() {
  const navigate = useNavigate()
  const [profile, setProfile] = useState(null); const [form, setForm] = useState(initial); const [step, setStep] = useState(0); const [existing, setExisting] = useState(null); const [checking, setChecking] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  useEffect(() => { (async () => { if (!supabase) return setChecking(false); const { data: { user } } = await supabase.auth.getUser(); if (!user) return setChecking(false); const [{ data: userProfile }, { data: plan }] = await Promise.all([supabase.from('profiles').select('province, health_risk_group').eq('id', user.id).maybeSingle(), supabase.from('health_plans').select('*').eq('user_id', user.id).order('created_at', { ascending: false }).limit(1).maybeSingle()]); setProfile(userProfile || {}); setExisting(plan || null); setChecking(false) })() }, [])
  async function createPlan(event) { event.preventDefault(); setSaving(true); try { const { data: { user } } = await supabase.auth.getUser(); const weight = num(form.weight); const height = num(form.height); const bodyMass = weight && height ? weight / ((height / 100) ** 2) : null; const plan = { days: Number(form.days), intensity: form.intensity, mode: 'ในร่มเป็นหลัก', bmi: bodyMass ? Number(bodyMass.toFixed(1)) : null, exercises: ['เดินเร็ว', 'ยืดเหยียด', 'ปั่นจักรยาน'] }; const { error } = await supabase.from('health_plans').insert({ user_id: user.id, age: num(form.age), weight_kg: weight, height_cm: height, days_per_week: plan.days, intensity: plan.intensity, chronic_condition: form.condition === 'อื่นๆ' ? form.otherCondition : form.condition, risk_group: profile?.health_risk_group || 'low', province: profile?.province || null, plan_json: plan }); if (error) throw error; navigate('/workout-plan', { state: { plan } }) } catch (error) { setMessage(error.message || 'บันทึกแผนไม่สำเร็จ') } finally { setSaving(false) } }
  async function removePlan() { if (!existing) return; setSaving(true); const { error } = await supabase.from('health_plans').delete().eq('id', existing.id); if (error) setMessage(error.message); else setExisting(null); setSaving(false) }
  if (checking) return <main className="health-planning-page exercise-plan-page"><div className="page-status">กำลังตรวจสอบแผนปัจจุบัน...</div></main>
  if (existing) return <main className="health-planning-page exercise-plan-page"><header className="health-planning-header"><Link to="/health-planning" className="health-planning-back">← กลับหน้าการวางแผน</Link><h1>คุณมีแผนการออกกำลังกายแล้ว</h1></header><section className="health-plan-card existing-plan-card"><strong>แผนปัจจุบันพร้อมใช้งาน</strong><div className="health-wizard-actions"><button className="health-primary-button" type="button" onClick={() => navigate('/workout-plan', { state: { plan: existing.plan_json || existing } })}>ดูแผนปัจจุบัน</button><button className="health-secondary-button" type="button" onClick={removePlan} disabled={saving}>ลบแผนเดิมเพื่อวางแผนใหม่</button></div></section></main>
  return <main className="health-planning-page exercise-plan-page"><header className="health-planning-header"><Link to="/health-planning" className="health-planning-back">← กลับหน้าการวางแผน</Link><h1>แผนการออกกำลังกาย</h1><p>ตอบคำถามทีละขั้นตอนเพื่อสร้างแผนที่เหมาะกับคุณ</p></header><form className="health-plan-card health-planning-form health-wizard exercise-plan-wizard" onSubmit={createPlan}><div className="health-stepper health-stepper-current"><span className="is-current">{step === 0 ? 'ร่างกาย' : step === 1 ? 'ความถี่' : 'สุขภาพ'}</span></div>{step === 0 && <><label>อายุ<input type="number" value={form.age} onChange={(e) => update('age', e.target.value)} required /></label><div className="health-form-row"><label>น้ำหนัก (กก.)<input type="number" step="0.1" value={form.weight} onChange={(e) => update('weight', e.target.value)} required /></label><label>ส่วนสูง (ซม.)<input type="number" step="0.1" value={form.height} onChange={(e) => update('height', e.target.value)} required /></label></div><button className="health-primary-button" type="button" onClick={() => setStep(1)}>ถัดไป →</button></>}{step === 1 && <><label>จำนวนวันต่อสัปดาห์<select value={form.days} onChange={(e) => update('days', e.target.value)}>{[1, 2, 3, 4, 5, 6, 7].map((day) => <option key={day}>{day}</option>)}</select></label><label>ระดับความหนัก<select value={form.intensity} onChange={(e) => update('intensity', e.target.value)}><option>เบา</option><option>ปานกลาง</option><option>หนัก</option></select></label><div className="health-wizard-actions"><button className="health-secondary-button" type="button" onClick={() => setStep(0)}>← ย้อนกลับ</button><button className="health-primary-button" type="button" onClick={() => setStep(2)}>ถัดไป →</button></div></>}{step === 2 && <><label>โรคประจำตัว<select value={form.condition} onChange={(e) => update('condition', e.target.value)}><option>ไม่มีโรคประจำตัว</option><option>หอบหืด</option><option>COPD</option><option>โรคหัวใจ</option><option>เบาหวาน</option><option>อื่นๆ</option></select></label>{form.condition === 'อื่นๆ' && <label>ระบุโรคประจำตัว<input value={form.otherCondition} onChange={(e) => update('otherCondition', e.target.value)} required /></label>}<div className="health-wizard-actions"><button className="health-secondary-button" type="button" onClick={() => setStep(1)}>← ย้อนกลับ</button><button className="health-primary-button" type="submit" disabled={saving}>{saving ? 'กำลังสร้าง...' : 'วางแผน'}</button></div></>}{message && <p className="health-form-note">{message}</p>}</form></main>
}
