import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const emptyHealth = { chronicCondition: 'ไม่มีโรคประจำตัว', medication: 'ไม่ได้ใช้ยาประจำ' }

export default function HealthTracker() {
  const navigate = useNavigate(); const [health, setHealth] = useState(emptyHealth); const [healthExists, setHealthExists] = useState(false); const [showHealthForm, setShowHealthForm] = useState(false); const [symptoms, setSymptoms] = useState(''); const [appointmentAt, setAppointmentAt] = useState(''); const [provider, setProvider] = useState(''); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { const timer = window.setTimeout(async () => { const { data: { user } } = await supabase.auth.getUser(); if (user) { const { data } = await supabase.from('health_profiles').select('chronic_condition, medication').eq('user_id', user.id).maybeSingle(); if (data) { setHealth({ chronicCondition: data.chronic_condition, medication: data.medication }); setHealthExists(true) } } setLoading(false) }, 0); return () => window.clearTimeout(timer) }, [])
  const updateHealth = (key, value) => setHealth((current) => ({ ...current, [key]: value }))
  function openHealthForm() { if (!healthExists) setHealth(emptyHealth); setMessage(''); setShowHealthForm(true) }
  async function saveHealth(event) { event.preventDefault(); setSaving(true); setMessage(''); try { const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from('health_profiles').upsert({ user_id: user.id, chronic_condition: health.chronicCondition, medication: health.medication, updated_at: new Date().toISOString() }); if (error) throw error; setHealthExists(true); setShowHealthForm(false); setMessage('บันทึกข้อมูลสุขภาพแล้ว') } catch (error) { setMessage(error.message || 'บันทึกข้อมูลสุขภาพไม่สำเร็จ') } finally { setSaving(false) } }
  async function saveAppointment(event) { event.preventDefault(); setSaving(true); setMessage(''); try { const { data: { user } } = await supabase.auth.getUser(); if (symptoms.trim()) { const { error } = await supabase.from('health_symptom_logs').insert({ user_id: user.id, symptoms: symptoms.trim() }); if (error) throw error } const { error } = await supabase.from('health_appointments').insert({ user_id: user.id, appointment_at: new Date(appointmentAt).toISOString(), provider: provider || null, notes: notes || null }); if (error) throw error; navigate('/appointments') } catch (error) { setMessage(error.message || 'ยืนยันการนัดหมายไม่สำเร็จ กรุณาตรวจสอบข้อมูลแล้วลองใหม่') } finally { setSaving(false) } }
  if (loading) return <main className="health-planning-page health-tracker-page"><p>กำลังตรวจสอบข้อมูลสุขภาพ...</p></main>
  const healthButtonLabel = healthExists ? 'แก้ไขข้อมูลสุขภาพ' : 'กรอกข้อมูลสุขภาพ'
  return <main className="health-planning-page health-tracker-page"><header className="health-planning-header"><Link to="/health-planning" className="health-planning-back">← กลับหน้าการวางแผน</Link><h1>ติดตามสุขภาพ ยา และนัดพบแพทย์</h1><p>จัดการข้อมูลสุขภาพและเพิ่มนัดหมายของคุณ</p><button className="health-secondary-button health-edit-profile-button" type="button" onClick={openHealthForm}>{healthButtonLabel}</button></header>{showHealthForm && <form className="health-plan-card health-planning-form health-profile-form" onSubmit={saveHealth}><h2>{healthExists ? 'แก้ไขข้อมูลสุขภาพ' : 'ข้อมูลสุขภาพครั้งแรก'}</h2><label>โรคประจำตัว<select value={health.chronicCondition} onChange={(event) => updateHealth('chronicCondition', event.target.value)}><option>ไม่มีโรคประจำตัว</option><option>หอบหืด</option><option>COPD</option><option>โรคหัวใจ</option><option>อื่นๆ</option></select></label><label>ยาที่ใช้ประจำ<select value={health.medication} onChange={(event) => updateHealth('medication', event.target.value)}><option>ไม่ได้ใช้ยาประจำ</option><option>ใช้ยาประจำ</option><option>อื่นๆ</option></select></label><div className="health-wizard-actions"><button className="health-primary-button" type="submit" disabled={saving}>{saving ? 'กำลังยืนยันการนัดหมาย...' : 'บันทึกข้อมูลสุขภาพ'}</button><button className="health-secondary-button" type="button" onClick={() => setShowHealthForm(false)}>ยกเลิก</button></div>{message && <p className="health-planning-status" role="status">{message}</p>}</form>}{!showHealthForm && <form className="health-plan-card health-planning-form" onSubmit={saveAppointment}><h2>เพิ่มรายละเอียดนัดหมาย</h2><label>อาการที่ต้องการติดตาม<textarea rows="4" value={symptoms} onChange={(event) => setSymptoms(event.target.value)} placeholder="เช่น ไอ เหนื่อย หรือไม่มีอาการ" /></label><label>วันและเวลา<input type="datetime-local" value={appointmentAt} onChange={(event) => setAppointmentAt(event.target.value)} required /></label><label>ชื่อแพทย์/สถานพยาบาล<input value={provider} onChange={(event) => setProvider(event.target.value)} /></label><label>หมายเหตุ<textarea rows="4" value={notes} onChange={(event) => setNotes(event.target.value)} /></label><button className="health-primary-button" type="submit" disabled={saving}>{saving ? 'กำลังยืนยันการนัดหมาย...' : 'ยืนยันการนัดหมาย'}</button>{message && <p className="health-planning-status" role="status">{message}</p>}</form>}</main>
}
