import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const NONE = 'ไม่มีโรคประจำตัว'
const NO_MED = 'ไม่ได้ใช้ยาประจำ'
const initial = { condition: NONE, otherCondition: '', medication: NO_MED, otherMedication: '', medicationName: '', medicationTime: '', appointmentAt: '', provider: '', preparation: '', bringItems: '' }

function Calendar({ month, setMonth, selected, setSelected, appointments }) {
  const days = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1); const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return Array.from({ length: 42 }, (_, i) => { const day = i - first.getDay() + 1; return day > 0 && day <= count ? new Date(month.getFullYear(), month.getMonth(), day) : null }) }, [month])
  return <div className="health-calendar"><div className="health-calendar-head"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>‹</button><strong>{month.toLocaleDateString('th-TH', { month: 'long', year: 'numeric' })}</strong><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>›</button></div><div className="health-calendar-week">{['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'].map((day) => <span key={day}>{day}</span>)}</div><div className="health-calendar-grid">{days.map((date, index) => { const key = date?.toISOString().slice(0, 10); const marked = date && appointments.some((item) => new Date(item.appointment_at).toDateString() === date.toDateString()); return <button key={index} type="button" disabled={!date} className={`health-calendar-day ${selected === key ? 'is-selected' : ''} ${marked ? 'has-appointment' : ''}`} onClick={() => date && setSelected(key)}>{date?.getDate()}</button> })}</div></div>
}

export default function HealthTracker() {
  const [step, setStep] = useState(0); const [form, setForm] = useState(initial); const [symptoms, setSymptoms] = useState(''); const [appointments, setAppointments] = useState([]); const [selected, setSelected] = useState(new Date().toISOString().slice(0, 10)); const [month, setMonth] = useState(new Date()); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from('health_appointments').select('*').eq('user_id', user.id).gte('appointment_at', new Date().toISOString()).order('appointment_at'); setAppointments(data || []) }
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [])
  async function save(event) { event.preventDefault(); setSaving(true); try { const { data: { user } } = await supabase.auth.getUser(); const condition = form.condition === 'อื่นๆ' ? form.otherCondition : form.condition; const medication = form.medication === 'อื่นๆ' ? form.otherMedication : form.medicationName; if (symptoms.trim()) { const { error } = await supabase.from('health_symptom_logs').insert({ user_id: user.id, symptoms: symptoms.trim() }); if (error) throw error } if (form.medication !== NO_MED && medication) { const { error } = await supabase.from('health_medications').insert({ user_id: user.id, name: medication, schedule_time: form.medicationTime, condition_name: condition, active: true }); if (error) throw error } const { error } = await supabase.from('health_appointments').insert({ user_id: user.id, appointment_at: new Date(form.appointmentAt).toISOString(), provider: form.provider || null, preparation: form.preparation, bring_items: form.bringItems }); if (error) throw error; await load(); setStep(1); setMessage('บันทึกนัดหมายแล้ว') } catch (error) { setMessage(error.message || 'บันทึกไม่สำเร็จ') } finally { setSaving(false) } }
  return <main className="health-planning-page health-tracker-page"><header className="health-planning-header"><Link to="/health-planning" className="health-planning-back">← กลับหน้าการวางแผน</Link><h1>ติดตามสุขภาพ ยา และนัดพบแพทย์</h1><p>ทำตามขั้นตอนทีละหน้าเพื่อบันทึกข้อมูลอย่างเป็นระบบ</p></header><div className="health-stepper health-stepper-current"><span className="is-current">{step === 0 ? 'อาการและสุขภาพ' : 'ปฏิทินและนัดหมาย'}</span></div>{message && <p className="health-planning-status health-planning-status--success">{message}</p>}{step === 0 && <section className="health-plan-card health-planning-form"><label>อาการที่ต้องการติดตาม<textarea rows="5" value={symptoms} onChange={(event) => setSymptoms(event.target.value)} /></label><label>โรคประจำตัว<select value={form.condition} onChange={(event) => update('condition', event.target.value)}><option>{NONE}</option><option>หอบหืด</option><option>COPD</option><option>โรคหัวใจ</option><option>เบาหวาน</option><option>อื่นๆ</option></select></label>{form.condition === 'อื่นๆ' && <label>ระบุโรคประจำตัว<input value={form.otherCondition} onChange={(event) => update('otherCondition', event.target.value)} required /></label>}<label>ยาที่ใช้ประจำ<select value={form.medication} onChange={(event) => update('medication', event.target.value)}><option>{NO_MED}</option><option>ใช้ยาประจำ</option><option>อื่นๆ</option></select></label>{form.medication === 'อื่นๆ' && <label>ระบุชื่อยา<input value={form.otherMedication} onChange={(event) => update('otherMedication', event.target.value)} required /></label>}{form.medication === 'ใช้ยาประจำ' && <label>ชื่อยา<input value={form.medicationName} onChange={(event) => update('medicationName', event.target.value)} required /></label>}<button className="health-primary-button" type="button" onClick={() => setStep(1)}>ไปเลือกวันนัด →</button></section>}{step === 1 && <form className="health-plan-card health-planning-form" onSubmit={save}><Calendar month={month} setMonth={setMonth} selected={selected} setSelected={setSelected} appointments={appointments} /><label>เวลา<input type="time" value={form.appointmentAt.split('T')[1] || ''} onChange={(event) => update('appointmentAt', selected + 'T' + event.target.value)} required /></label><label>ชื่อแพทย์/สถานพยาบาล<input value={form.provider} onChange={(event) => update('provider', event.target.value)} /></label><label>การเตรียมตัว<textarea rows="3" value={form.preparation} onChange={(event) => update('preparation', event.target.value)} required /></label><label>สิ่งที่ต้องนำไป<textarea rows="3" value={form.bringItems} onChange={(event) => update('bringItems', event.target.value)} required /></label><div className="health-wizard-actions"><button className="health-secondary-button" type="button" onClick={() => setStep(0)}>← ย้อนกลับ</button><button className="health-primary-button" type="submit" disabled={saving}>{saving ? 'กำลังบันทึก...' : 'บันทึกนัดหมาย'}</button></div></form>}</main>
}
