import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { getAirQualityStations, getOpenMeteoAirQuality } from '../services/airQuality'
import { getAqiStatus } from '../utils/aqiStatus'

const REGIONS = {
  เหนือ: ['เชียงใหม่', 'เชียงราย', 'แม่ฮ่องสอน', 'ลำปาง', 'ลำพูน', 'น่าน', 'พะเยา', 'แพร่', 'อุตรดิตถ์', 'พิษณุโลก', 'สุโขทัย', 'เพชรบูรณ์', 'กำแพงเพชร', 'พิจิตร', 'ตาก'],
  'ตะวันออกเฉียงเหนือ': ['นครราชสีมา', 'ขอนแก่น', 'อุบลราชธานี', 'อุดรธานี', 'ร้อยเอ็ด', 'บุรีรัมย์', 'สกลนคร', 'กาฬสินธุ์', 'ชัยภูมิ', 'นครพนม', 'บึงกาฬ', 'มหาสารคาม', 'มุกดาหาร', 'ยโสธร', 'เลย', 'ศรีสะเกษ', 'สุรินทร์', 'หนองคาย', 'หนองบัวลำภู', 'อำนาจเจริญ'],
  กลาง: ['กรุงเทพมหานคร', 'กรุงเทพ', 'นนทบุรี', 'ปทุมธานี', 'ชลบุรี', 'สมุทรปราการ', 'พระนครศรีอยุธยา', 'ระยอง', 'กาญจนบุรี', 'นครปฐม', 'ราชบุรี', 'ลพบุรี', 'สระบุรี', 'สมุทรสาคร', 'สมุทรสงคราม', 'สุพรรณบุรี', 'จันทบุรี', 'ฉะเชิงเทรา', 'ตราด', 'นครนายก', 'ปราจีนบุรี', 'สระแก้ว'],
  ใต้: ['สงขลา', 'ภูเก็ต', 'นครศรีธรรมราช', 'สุราษฎร์ธานี', 'ยะลา', 'นราธิวาส', 'ตรัง', 'กระบี่', 'ชุมพร', 'พังงา', 'พัทลุง', 'สตูล', 'ปัตตานี', 'ระนอง'],
}
const FALLBACKS = { เหนือ: [['เชียงใหม่', 18.7883, 98.9853], ['เชียงราย', 19.9105, 99.8406], ['ลำปาง', 18.2888, 99.4928]], 'ตะวันออกเฉียงเหนือ': [['ขอนแก่น', 16.4322, 102.8236], ['นครราชสีมา', 14.9799, 102.0978], ['อุดรธานี', 17.4138, 102.7870]], กลาง: [['กรุงเทพมหานคร', 13.7563, 100.5018], ['ชลบุรี', 13.3611, 100.9847], ['พระนครศรีอยุธยา', 14.3532, 100.5684]], ใต้: [['ภูเก็ต', 7.8804, 98.3923], ['สงขลา', 7.1897, 100.5951], ['นครศรีธรรมราช', 8.4304, 99.9631]] }

function normalize(value) { return String(value || '').toLocaleLowerCase('th-TH').replace(/จังหวัด|province|prov\.?/gi, '').replace(/[\s,.-]/g, '') }
function numericPm(value) { const parsed = Number.parseFloat(String(value ?? '').replace(',', '.')); return Number.isFinite(parsed) && parsed > 0 ? parsed : null }
function pm25ToAqi(pm25) { const value = numericPm(pm25); if (value === null) return null; const points = [[0, 9, 0, 50], [9.1, 35.4, 51, 100], [35.5, 55.4, 101, 150], [55.5, 125.4, 151, 200], [125.5, 225.4, 201, 300], [225.5, 325.4, 301, 500]]; const [lowC, highC, lowI, highI] = points.find(([low, high]) => value >= low && value <= high) || points.at(-1); return Math.round(((highI - lowI) / (highC - lowC)) * (Math.min(value, highC) - lowC) + lowI) }
function findProvince(station, region) { const text = normalize([station.province, station.locationText, station.name].join(' ')); return REGIONS[region].find((province) => text.includes(normalize(province))) || null }
function groupRows(stations) { return Object.keys(REGIONS).map((region) => { const grouped = {}; stations.forEach((station) => { const province = findProvince(station, region); const pm25 = numericPm(station.pm25); if (province && pm25 !== null) (grouped[province] ||= []).push(pm25) }); return { region, top: Object.entries(grouped).map(([province, values]) => { const pm25 = values.reduce((sum, value) => sum + value, 0) / values.length; return { province, pm25, aqi: pm25ToAqi(pm25) } }).sort((a, b) => b.aqi - a.aqi).slice(0, 3) } }) }
function fillTopThree(rows) { return rows.map((row) => { const used = new Set(row.top.map((item) => normalize(item.province))); const fallback = FALLBACKS[row.region].filter(([province]) => !used.has(normalize(province))).map(([province]) => ({ province, pm25: null, aqi: null })); return { ...row, top: [...row.top, ...fallback].slice(0, 3) } }) }
async function fetchFallbacks(rows) { const requests = rows.flatMap((row) => FALLBACKS[row.region].map(async ([province, latitude, longitude]) => { if (row.top.some((item) => normalize(item.province) === normalize(province) && item.aqi !== null)) return null; try { const result = await getOpenMeteoAirQuality(latitude, longitude); return { province, locationText: province, name: province, pm25: result.pm25 } } catch { return null } })); return (await Promise.all(requests)).filter(Boolean) }
function groupRisk(aqi) { const status = getAqiStatus(aqi); return { tone: status.tone, label: status.label } }
function advice(aqi, group) { if (group === 'sensitive') return aqi === null || aqi > 100 ? 'ควรลดเวลาทำกิจกรรมนอกอาคารและสวมหน้ากาก N95' : 'ควรติดตามค่า AQI และสวมหน้ากาก N95 เมื่ออยู่กลางแจ้ง'; if (aqi === null || aqi > 150) return 'หลีกเลี่ยงกิจกรรมนอกอาคารและติดตามประกาศสุขภาพ'; if (aqi > 100) return 'ลดกิจกรรมนอกอาคารและสวมหน้ากากที่ป้องกัน PM2.5'; if (aqi > 50) return 'ลดกิจกรรมกลางแจ้งที่ใช้แรงมากและสังเกตอาการ'; return 'ทำกิจกรรมได้ตามปกติและติดตามค่าฝุ่นอย่างสม่ำเสมอ' }
function Donut({ value }) { const percent = Math.min(100, Math.max(0, ((value || 0) / 500) * 100)); return <div className="regional-donut"><svg viewBox="0 0 42 42"><circle className="regional-donut-track" cx="21" cy="21" r="15.9155" /><circle className="regional-donut-value" cx="21" cy="21" r="15.9155" pathLength="100" strokeDasharray={`${percent} ${100 - percent}`} /></svg><div className="regional-donut-label"><strong>{value === null ? 'รอข้อมูล' : value}</strong><small>AQI</small></div></div> }
function RegionalCard({ row, group }) { const values = row.top.filter((item) => item.aqi !== null); const average = values.length ? Math.round(values.reduce((sum, item) => sum + item.aqi, 0) / values.length) : null; const risk = groupRisk(average); return <article className={`regional-card regional-card--${risk.tone}`}><header className="regional-card-header"><div className="regional-icon">◈</div><div><h2>ภาค{row.region}</h2></div></header><div className="regional-summary"><Donut value={average} /><span className={`regional-status regional-status--${risk.tone}`}>{risk.label}</span></div><section className="regional-top"><h3>3 จังหวัดฝุ่นสูงสุด</h3>{row.top.map((item, index) => <div className="regional-province-row" key={`${row.region}-${item.province}`}><span className="regional-rank">{index + 1}</span><strong>{item.province}</strong><b>{item.aqi === null ? 'รอข้อมูล' : `AQI ${item.aqi}`}</b></div>)}</section><p className="regional-advice">{advice(average, group)}</p></article> }
function runSelfTest() { const complete = Object.keys(REGIONS).flatMap((region) => FALLBACKS[region].map(([province]) => ({ province, locationText: province, pm25: 20 }))); const sparse = [{ province: 'ภูเก็ต', locationText: 'ภูเก็ต', pm25: 55 }]; const result = { complete: groupRows(complete).every((row) => fillTopThree(groupRows(complete)).find((item) => item.region === row.region).top.length === 3), sparse: fillTopThree(groupRows(sparse)).every((row) => row.top.length === 3), aqi: pm25ToAqi(15) === 56, badge: groupRisk(120).label === 'กลุ่มเสี่ยงควรระวัง' }; console.info('[Regional Dashboard Self-Test]', { ...result, passed: Object.values(result).every(Boolean) }) }
if (import.meta.env.DEV) runSelfTest()

export default function RegionalDashboard() { const [state, setState] = useState({ status: 'loading', stations: [], group: 'normal', error: '' }); useEffect(() => { let cancelled = false; Promise.all([supabase.from('profiles').select('health_risk_group').maybeSingle(), getAirQualityStations(0, 0)]).then(async ([profile, stations]) => { const valid = stations.filter((station) => numericPm(station.pm25) !== null); const fallback = await fetchFallbacks(groupRows(valid)); const group = profile.data?.health_risk_group === 'high_critical' ? 'sensitive' : 'normal'; if (!cancelled) setState({ status: 'ready', stations: [...valid, ...fallback], group, error: '' }) }).catch((error) => { if (!cancelled) setState({ status: 'error', stations: [], group: 'normal', error: error.message || 'ไม่สามารถโหลดข้อมูลภาพรวมได้' }) }); return () => { cancelled = true } }, []); const rows = useMemo(() => fillTopThree(groupRows(state.stations)), [state.stations]); if (state.status === 'loading') return <main className="regional-dashboard-page"><p>กำลังโหลดภาพรวมสถานการณ์ฝุ่น...</p></main>; if (state.status === 'error') return <main className="regional-dashboard-page"><p className="regional-error">{state.error}</p></main>; return <main className="regional-dashboard-page"><header className="regional-dashboard-header"><div><h1>ภาพรวมสถานการณ์ฝุ่น PM2.5</h1><p>กลุ่มผู้ใช้งาน: {state.group === 'sensitive' ? 'กลุ่มเสี่ยง/กลุ่มเปราะบาง' : 'กลุ่มทั่วไป'} · แสดงค่า AQI</p></div><Link to="/" className="regional-back-link">กลับหน้าหลัก</Link></header><section className="regional-grid">{rows.map((row) => <RegionalCard key={row.region} row={row} group={state.group} />)}</section><section className="regional-legend"><h2>ระดับ AQI จาก PM2.5</h2><div className="regional-color-bar"><span className="regional-legend-low">0–50</span><span className="regional-legend-mid">51–100</span><span className="regional-legend-watch">101–150</span><span className="regional-legend-high">151–200</span><span className="regional-legend-critical">201+</span></div><div className="regional-legend-labels"><span>ดี</span><span>ปานกลาง</span><span>กลุ่มเสี่ยงควรระวัง</span><span>มีผลกระทบ</span><span>อันตราย</span></div></section></main> }
